# Generated by Django 4.2.6 on 2023-11-02 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_logs_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='vendor',
            field=models.CharField(max_length=100),
        ),
    ]
